services:
  joy-memorial:
    image: joy-memorial
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=joymem;User Id=sa;Password=peninsulated96"
  db:
    build:
      context: .
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: peninsulated96
    ports:
      - "1433:1433"
 